<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-25KQ22H" failures="1" tests="1" name="Default test" time="0.089" errors="0" timestamp="2024-07-29T14:04:33 IST">
  <testcase classname="testng.test.Assertion" name="testMethodCheckAsserEqualWithErrorMessage" time="0.026">
    <failure type="java.lang.AssertionError" message="Actual value and Expected values are different expected [30] but found [20]">
      <![CDATA[java.lang.AssertionError: Actual value and Expected values are different expected [30] but found [20]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at testng.test.Assertion.testMethodCheckAsserEqualWithErrorMessage(Assertion.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testMethodCheckAsserEqualWithErrorMessage -->
  <testcase classname="testng.test.Assertion" name="testMethodSoftAssertion" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodSoftAssertion -->
  <testcase classname="testng.test.Assertion" name="testMethodCheckAssertNull" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodCheckAssertNull -->
  <testcase classname="testng.test.Assertion" name="testMethodCheckAssertFalse" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodCheckAssertFalse -->
  <testcase classname="testng.test.Assertion" name="testMethodCheckAssertEqual" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodCheckAssertEqual -->
  <testcase classname="testng.test.Assertion" name="testMethodCheckAssertTrue" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodCheckAssertTrue -->
  <testcase classname="testng.test.Assertion" name="testMethodCheckAssertNotNull" time="0.0">
    <ignored/>
  </testcase> <!-- testMethodCheckAssertNotNull -->
</testsuite> <!-- Default test -->
